resources:
# Application source repository
  - name: adir_git
    type: GitRepo
    configuration:
      gitProvider: Github
      path: AdirGali/jfrogCI
      branches: 
        include: main
      buildOn:
        commit: true

  - name: adir_build
    type: BuildInfo
    configuration:
      sourceArtifactory: Artifactory      



# Docker image in an Artifactory repository
#  - name: adir_arti
    # type: Image
    # configuration:
    #   registry: Artifactory
    #   sourceRepository: adirg-task/
    #   imageName: jfrogtask1
    #   imageTag: latest
    #   autoPull: true
      
pipelines:
  - name: adir_pipelines
    steps:
      - name: build_image
        type: DockerBuild
        configuration:
          affinityGroup: adir_group
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: pe16362adirg.jfrog.io/adirg-task/jfrogtask1
          dockerImageTag: ${run_number}
          inputResources:
            - name: adir_git
          integrations:
            - name: Artifactory

      - name: docker_push
        type: DockerPush
        configuration:
          affinityGroup: adir_group
          targetRepository: adirg-task
          # forceXrayScan: true 
          integrations:
            - name: Artifactory                     # <-- replace with your artifactory integration
          inputSteps:
            - name: build_image

      - name: publish_build
        type: PublishBuildInfo
        configuration:
          # forceXrayScan: true
          affinityGroup: adir_group
          inputSteps:
             - name: docker_push
          outputResources:
             - name: adir_build   

      - name: adir_xray
        type: XrayScan
        configuration:
          affinityGroup: adir_group
          inputResoursces:
            - name: adir_build




#  - name: adir_pipline
#    steps:
#      - name: printenv
#        type: Bash
#        configuration:
#          inputResources:
#            - name: adir_git
#        execution:
#          onExecute:
#            - printenv
#            - ls