resources:
# Application source repository
  - name: adir_git
    type: GitRepo
    configuration:
      gitProvider: Github
      path: AdirGali/jfrogCI
      branches: 
        include: main

# Docker image in an Artifactory repository
  - name: adir_arti
    type: Image
    configuration:
      registry: Artifactory
      sourceRepository: adirg-task/
      imageName: jfrogtask1
      imageTag: latest
      autoPull: true
      
pipelines:
  - name: adir_pipline
    steps:
      - name: build_image
        type: DockerBuild
        configuration:
          dockerFileLocation: .
          dockerFileName: dockerfile
          dockerImageName: pe16362adirg.jfrog.io/adirg-task/jfrogtask1:latest
          dockerImageTag: latest
          inputResources:
            - name: adir_git
          integrations:
            - name: Github


